/**
 * Fixed legal text.
 *
 * NOT generated. NOT editable through the UI. NOT conditionally omitted for
 * any reason (readme.md structural rule 4, PRD 7.4, 11.2).
 *
 * ---------------------------------------------------------------------------
 * GATE D2 (plan.md) - THIS TEXT IS NOT YET CLEARED FOR CLIENT DELIVERY.
 *
 * PRD OPEN-09: the wording below is a reasonable draft, is NOT legal advice,
 * and has NOT been reviewed by a lawyer. The SEBI terminology in particular
 * must be checked against Klawfin's actual (currently unincorporated) status.
 *
 * No report goes to a paying founder until Dhruv has signed this off against
 * actual legal input. `DISCLAIMER_APPROVAL` below is the switch, and the
 * report renders a visible PENDING LEGAL SIGN-OFF marker until it is flipped.
 * That marker is deliberately impossible to miss: shipping placeholder legal
 * text to a paying client is the failure this whole module exists to prevent.
 * ---------------------------------------------------------------------------
 */

/**
 * Whether the disclaimer wording has been signed off by Dhruv against counsel
 * input (plan.md gate D2, PRD OPEN-09).
 *
 * Flipping this to `approved` is a deliberate commit that must reference the
 * decision record in docs/decisions/. It is intentionally a source constant
 * and not an environment variable: a legal sign-off is a reviewed code change,
 * not a runtime toggle someone can flip at 11pm before a client meeting.
 */
export const DISCLAIMER_APPROVAL = {
  status: 'pending_legal_review' as 'pending_legal_review' | 'approved',
  /** Set both when status becomes 'approved'. */
  approvedBy: null as string | null,
  approvedOn: null as string | null,
  decisionRecord: 'docs/decisions/0009-disclaimer-wording.md',
} as const;

export function isDisclaimerApproved(): boolean {
  return DISCLAIMER_APPROVAL.status === 'approved';
}

/**
 * Full disclaimer. Appears in full on the disclaimer page of every report
 * (PRD 7.1 section 2, 11.2).
 */
export const DISCLAIMER_FULL = `This report is a business assessment prepared by Klawfin for the named company about its own fundraising preparedness. It is not investment advice, not a recommendation to buy, sell or hold any security, and not a solicitation or offer of any kind. Klawfin is not registered with the Securities and Exchange Board of India as an investment adviser, research analyst, or merchant banker, and holds no securities licence. The assessment reflects information supplied by the company and Klawfin's structured review of it; it has not been independently audited or verified. Scores are an internal diagnostic produced by Klawfin's readiness rubric and are not a rating, a valuation, or a prediction of fundraising outcome. Nothing in this document should be relied upon by any third party. The company should obtain independent legal, financial and tax advice before acting on any recommendation contained here.`;

/**
 * Short disclaimer. Appears in the footer of EVERY page (PRD P1-08, 11.2).
 *
 * The PDF renderer places this in a fixed footer so it cannot be omitted by a
 * page-break accident. There is no code path that renders a report page
 * without it.
 */
export const DISCLAIMER_SHORT = `Business assessment only - not investment advice, not a solicitation. Klawfin holds no securities licence.`;

/** Marker rendered while DISCLAIMER_APPROVAL.status is 'pending_legal_review'. */
export const DISCLAIMER_PENDING_MARKER = `PENDING LEGAL SIGN-OFF - NOT FOR CLIENT DELIVERY`;

/** Confidentiality marking carried on every page (PRD 7.3). */
export function confidentialityMarking(clientName: string): string {
  return `Confidential - prepared for ${clientName}`;
}

/**
 * Watermark for a report generated below the minimum coverage threshold with
 * an explicit override (PRD 8.1).
 */
export const WATERMARK_INCOMPLETE = `PRELIMINARY - INCOMPLETE DATA`;

/** Label for a report generated between 60% and 80% coverage (PRD 8.1). */
export const LABEL_PRELIMINARY = `Preliminary`;

/**
 * Methodology text for the report's final section (PRD 7.1 section 12).
 *
 * States what the score is and, more importantly, what it is not. Template
 * text, never generated.
 */
export const METHODOLOGY_TEXT = `This assessment scores six dimensions of fundraising readiness against a fixed rubric. Each dimension contains sub-criteria scored on a 0-4 anchored scale, where 0 means absent, 2 means real work exists with material holes, and 4 means a reason to invest rather than the absence of a reason not to. Sub-criterion scores are combined into a dimension percentage, and dimensions are weighted to produce a composite score from 0 to 100.

Scoring is deterministic: the same information produces the same score every time. Scores are computed from the structured information recorded during the engagement, not generated by a language model. Where a sub-criterion does not apply to this company, it is excluded from the calculation rather than scored zero, and this report states where that happened.

Coverage indicates how much of the information the rubric asks for was available. A score at low coverage is a less reliable score, and this report labels it as such rather than presenting it with false confidence.

This score is an internal readiness diagnostic. It is not a rating, not a credit assessment, not an investability grade, not a valuation, and not a prediction of whether this company will raise. It is not comparable to any score produced by any other party, and it is not a signal intended for, or to be relied upon by, any third party.`;

/**
 * Statement inserted when the assessment ran in pre-revenue mode (PRD 8.4).
 *
 * Required so a pre-revenue traction score is not misread as comparable to a
 * revenue-stage company's.
 */
export const PRE_REVENUE_NOTICE = `Traction for this company was assessed against pre-revenue evidence - signed commitments, documented customer discovery, design partners and leading indicators - rather than revenue. The Traction & Validation score is therefore not directly comparable to that of a revenue-stage company, and should not be read as one.`;

/** Statement inserted when a dimension's weight was redistributed (PRD 5.5). */
export const WEIGHT_REDISTRIBUTED_NOTICE = `One or more dimensions did not apply to this company and were excluded from scoring. Their weight has been redistributed proportionally across the remaining dimensions, and the dimension table below shows the weight actually applied.`;

/**
 * Every fixed string that must survive to the rendered report, for the export
 * test that asserts none of them was dropped.
 */
export const REQUIRED_REPORT_STRINGS = [DISCLAIMER_FULL, DISCLAIMER_SHORT, METHODOLOGY_TEXT] as const;
