/**
 * Composite score bands (PRD 5.6).
 *
 * Band language is fixed, client-facing template text. It is NOT generated by
 * the model and is not editable in the application: a band is a readiness
 * diagnostic, not an endorsement and not a prediction of outcome (PRD 11.1).
 */

import type { Band, Confidence } from './types.js';

export const BANDS: readonly Band[] = [
  {
    id: 'not_raise_ready',
    label: 'Not raise-ready',
    min: 0,
    max: 39,
    meaning:
      'Material work required across multiple dimensions before approaching investors. Approaching now will burn relationships that are hard to re-open.',
  },
  {
    id: 'significant_gaps',
    label: 'Significant gaps',
    min: 40,
    max: 59,
    meaning:
      'A raise is possible but will be slow and will likely be done from a weak position. Specific gaps are addressable.',
  },
  {
    id: 'raise_capable_with_fixes',
    label: 'Raise-capable with fixes',
    min: 60,
    max: 74,
    meaning:
      'Fundamentally fundable. Named gaps will cost time and terms if not closed first.',
  },
  {
    id: 'raise_ready',
    label: 'Raise-ready',
    min: 75,
    max: 100,
    meaning: 'Prepared. Remaining work is refinement and process, not substance.',
  },
] as const;

/**
 * Resolve a band from an integer composite.
 *
 * @param composite Integer 0-100, already rounded (PRD 5.5: round once, at the end).
 */
export function bandFor(composite: number): Band {
  if (!Number.isFinite(composite)) {
    throw new Error(`Composite must be finite; got ${composite}`);
  }
  const clamped = Math.min(100, Math.max(0, composite));
  const band = BANDS.find((b) => clamped >= b.min && clamped <= b.max);
  if (!band) {
    // Unreachable given the ranges above cover 0-100 contiguously, but a
    // silent undefined here would put a blank band on a client PDF.
    throw new Error(`No band defined for composite ${composite}`);
  }
  return band;
}

/** Coverage thresholds for dimension confidence (PRD 5.5). */
export const CONFIDENCE_THRESHOLDS = { high: 0.8, medium: 0.6 } as const;

export function confidenceFor(coverage: number): Confidence {
  if (coverage >= CONFIDENCE_THRESHOLDS.high) return 'high';
  if (coverage >= CONFIDENCE_THRESHOLDS.medium) return 'medium';
  return 'low';
}

/**
 * Overall coverage thresholds that gate generation (PRD 8.1).
 *
 * - >= 0.80  generate normally
 * - >= 0.60  generate, mark the report "Preliminary"
 * -  < 0.60  block by default; override is explicit and recorded
 */
export const COVERAGE_GATES = {
  normal: 0.8,
  preliminary: 0.6,
  /** Below this, a single dimension is reported as "not assessed" (PRD 8.1). */
  dimensionNotAssessed: 0.4,
} as const;

export type CoverageDisposition = 'normal' | 'preliminary' | 'blocked';

export function coverageDisposition(overallCoverage: number): CoverageDisposition {
  if (overallCoverage >= COVERAGE_GATES.normal) return 'normal';
  if (overallCoverage >= COVERAGE_GATES.preliminary) return 'preliminary';
  return 'blocked';
}
