// @ts-check

/**
 * Lint configuration for the whole workspace.
 *
 * ONE config at the root rather than one per package. The packages had no
 * linting at all, and the web app's `next lint` had no configuration to find -
 * it dropped into an interactive setup prompt, so `pnpm lint` could never have
 * passed in CI or on a fresh clone.
 *
 * Flat config, because `next lint` is deprecated and removed in Next.js 16.
 *
 * WHAT THIS IS FOR: catching mistakes, not enforcing taste. Formatting rules
 * are deliberately absent - they generate diff noise that buries real findings,
 * and a team of four reviewing each other's work does not need a linter to
 * argue about quote marks.
 */

import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import nextPlugin from '@next/eslint-plugin-next';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/.next/**',
      '**/dist/**',
      '**/coverage/**',
      '**/*.tsbuildinfo',
      'supabase/**',
      // Generated by Next on every build; not ours to lint or fix.
      '**/next-env.d.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    rules: {
      /**
       * An unused variable is usually a leftover from a change that is not
       * finished. The underscore escape hatch exists for the cases where the
       * signature is fixed by someone else - a route handler's unused
       * `request`, a caught error nobody needs to inspect.
       */
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrors: 'none',
        },
      ],

      /**
       * `any` defeats the entire point of the strict TypeScript settings this
       * project runs with. A warning rather than an error: it is occasionally
       * the honest answer at a boundary with an untyped library, and a rule
       * people routinely disable inline is worse than one they see.
       */
      '@typescript-eslint/no-explicit-any': 'warn',

      // The codebase uses `interface` and `type` for different reasons - see
      // the load-bearing comment in lib/db/types.ts about supabase-js needing
      // an index signature. A style rule here would break real code.
      '@typescript-eslint/consistent-type-definitions': 'off',
    },
  },

  /**
   * Next.js rules, scoped to the app.
   *
   * These are about Next-specific correctness - an `<img>` that should be
   * `next/image`, a `<a>` where a `<Link>` belongs, a synchronous script in the
   * wrong place. They mean nothing in the pure packages.
   */
  {
    files: ['apps/web/**/*.{ts,tsx}'],
    plugins: { '@next/next': nextPlugin },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      // App Router only. The rule looks for a pages/ directory, does not find
      // one, and warns on every run about a structure this app does not use.
      '@next/next/no-html-link-for-pages': 'off',
    },
  },

  /**
   * Tests reach into internals and build deliberately malformed values to
   * prove the validators reject them. Both are the job, not a smell.
   */
  {
    files: ['**/tests/**/*.{ts,tsx}', '**/*.test.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },

  /**
   * Config files and build scripts run in Node and legitimately reach for its
   * globals. Without this, `scripts/check-palette.mjs` - which exists to fail
   * the build - could not itself pass the build.
   */
  {
    files: ['*.config.{ts,mjs,js}', '**/*.config.{ts,mjs,js}', 'scripts/**/*.{mjs,js,ts}'],
    languageOptions: {
      globals: {
        process: 'readonly',
        console: 'readonly',
        __dirname: 'readonly',
        Buffer: 'readonly',
        // Web-standard globals that Node has had since 18. `fetch` in
        // particular is why scripts/demo.mjs needs no Supabase client
        // dependency to talk to PostgREST and the auth admin API.
        fetch: 'readonly',
        URL: 'readonly',
        AbortSignal: 'readonly',
        setTimeout: 'readonly',
      },
    },
  },
);
